# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 263)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1141, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.part_table = QtWidgets.QTableWidget(self.tab)
        self.part_table.setEnabled(True)
        self.part_table.setGeometry(QtCore.QRect(310, 0, 661, 181))
        self.part_table.setRowCount(6)
        self.part_table.setColumnCount(5)
        self.part_table.setObjectName("part_table")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 73, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 0, 201, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.part_name_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.part_name_edit.setObjectName("part_name_edit")
        self.verticalLayout_2.addWidget(self.part_name_edit)
        self.part_mealege_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.part_mealege_edit.setObjectName("part_mealege_edit")
        self.verticalLayout_2.addWidget(self.part_mealege_edit)
        self.part_price = QtWidgets.QLineEdit(self.layoutWidget1)
        self.part_price.setObjectName("part_price")
        self.verticalLayout_2.addWidget(self.part_price)
        self.part_date_edit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.part_date_edit.setObjectName("part_date_edit")
        self.verticalLayout_2.addWidget(self.part_date_edit)
        self.part_note_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.part_note_edit.setObjectName("part_note_edit")
        self.verticalLayout_2.addWidget(self.part_note_edit)
        self.addBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.addBtn.setEnabled(True)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout_2.addWidget(self.addBtn)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Autotool v1.0"))
        self.label.setText(_translate("MainWindow", "Назва ЗЧ"))
        self.label_2.setText(_translate("MainWindow", "Пробіг, км"))
        self.label_3.setText(_translate("MainWindow", "Ціна, грн"))
        self.label_4.setText(_translate("MainWindow", "Дата заміни"))
        self.label_5.setText(_translate("MainWindow", "Примітка"))
        self.addBtn.setText(_translate("MainWindow", "Додати заміну"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Заміни запчастин та ТО"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Заправки авто"))
        self.part_table.setHorizontalHeaderLabels(["№", "Назва", "Ціна, грн", "Дата заміни", "Пробіг, км"])
        self.part_table.setToolTip("Сюди записуємо дані")
        self.part_table.horizontalHeaderItem(0).setToolTip("Номер запису")
        self.part_table.horizontalHeaderItem(1).setToolTip(
            "Назва вузла, деталі, витратного матеріалу, що мінявся/ставився")
        self.part_table.horizontalHeaderItem(2).setToolTip("Вартість заміненої деталі")
        self.part_table.horizontalHeaderItem(3).setToolTip("Тут вказати дату заміни")
        self.part_table.horizontalHeaderItem(4).setToolTip("Тут вказати пробіг в км. на момент заміни деталі")
        self.part_table.verticalHeader().setVisible(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
